Vagrant.configure("2") do |config|
        config.vm.define "Rocky8" do |rocky|
        rocky.vm.box = "generic/rocky8"
        rocky.vm.hostname = 'rocky'
        rocky.vm.network "public_network", ip: "192.168.3.198"
        rocky.vm.provision "shell", inline: <<-SHELL
                sudo yum install tmux httpd mod_ssl -y
        SHELL
        rocky.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--memory", 512]
          v.customize ["modifyvm", :id, "--name", "Rocky"]
        end
     end
        config.vm.define "Debian" do |debian|
        debian.vm.box = "debian/buster64"
        debian.vm.hostname = 'Debian'
        debian.vm.network "public_network", ip: "192.168.3.199"
        debian.vm.provision "shell", inline: <<-SHELL
                sudo apt-get --allow-releaseinfo-change update
                sudo apt-get install tmux apache2 -y
        SHELL
        debian.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "Debian"]
        end 
     end
end
