Vagrant.configure("2") do |config|
    config.vm.define "Rocky8" do |rocky|
    rocky.vm.box = "generic/rocky8"
    rocky.vm.hostname = 'rocky'
    rocky.vm.network "public_network", ip: "192.168.3.198"
    rocky.vm.provision "shell", inline: <<-SHELL
       yum install httpd mod_ssl -y
    SHELL
    rocky.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "rocky"]
    end
  end
end
